version: '3.5'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/htpasswd:/etc/nginx/htpasswd
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
#      - ./conf.d/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-letsencrypt:
    depends_on:
      - nginx-proxy
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

# Create network if it does not exist
networks: { proxy: { name: proxy } }
